# Controls when the workflow will run
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0/45 * * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  render:
    name: Render my document
    runs-on: macOS-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - uses: r-lib/actions/setup-tinytex@v1

      # Runs a single command using the runners shell
      - name: Install rmarkdown and dependent packages
        run: |-
          install.packages("remotes")
          remotes::install_cran("rmarkdown")
          remotes::install_cran(c("plyr", "dplyr", "lubridate", "leaflet", "RColorBrewer","readr","purrr"))
        shell: Rscript {0}
      - name: Render my document to all types
        run: Rscript -e 'rmarkdown::render("index.Rmd", output_format = "html_document")'
      - name: Commit results
        run: |
          git add index.html
          git commit -m 'Re-build index.html' || echo "No changes to commit"
          git push origin || echo "No changes to commit"

